### ISSUE TITLE
"undefined is not a function" stats in node4/npm3

### ISSUE THREAD

**Issue by jreading** [jsdoc2md/jsdoc-to-markdown#103]
struggling to to get to work for my build

`node_modules/app-usage-stats/es5/lib/app-usage-stats.js:195
          throw err;
                ^
TypeError: undefined is not a function
    at _loop (/node_modules/app-usage-stats/es5/lib/stats.js:29:34)
    at Stats.add (/node_modules/app-usage-stats/es5/lib/stats.js:96:11)
    at AppUsageStats.loadSync (/node_modules/app-usage-stats/es5/lib/app-usage-stats.js:192:21)
    at new JsdocToMarkdownStats (/node_modules/jsdoc2md-stats/es5/jsdoc2md-stats.js:63:20)
    at Object.<anonymous> (/node_modules/jsdoc-to-markdown/es5/lib/jsdoc-to-markdown.js:97:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)`

**Comment by 75lb** [comment]
Hi.. 

i can't reproduce this.. also, [app-usage-stats/es5/lib/stats.js line 29](https://github.com/75lb/app-usage-stats/blob/master/es5/lib/stats.js#L29) does not match what your error stack is reporting.. 

Did you try uninstalling then reinstalling jsdoc2md? Which version of jsdoc2md are you using?

**Comment by jreading** [comment]
I'm setting up a super simple job that just runs the gulp demo you have.

**Comment by 75lb** [comment]
ok, great! but i'm trying to reproduce your issue and your reply moved me no closer to achieving that.. 

could you send some reproduction steps, please.. like i said before, the stack trace you posted is referencing old code so something else has gone wrong, possibly with npm..

**Comment by 75lb** [comment]
ok, glad you found the source of the issue.
