### ISSUE TITLE
Getting `Cannot read property '_stats' of undefined` when using the `render` function

### ISSUE THREAD

**Issue by Haroenv** [jsdoc2md/jsdoc-to-markdown#127]
Stack trace: 

```
my-project/node_modules/jsdoc2md-stats/lib/jsdoc2md-stats.js:113
      return this._stats(super.render, options)
                 ^

TypeError: Cannot read property '_stats' of undefined
    at render (my-project/node_modules/jsdoc2md-stats/lib/jsdoc2md-stats.js:113:18)
    at Object.<anonymous> (my-project/test.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
```

```js
// the file
const { render } = require('jsdoc-to-markdown');

render({ source: '/** example doclet */ \n var example = true' }).then(
  console.log
);
```

**Comment by 75lb** [comment]
in your example code, the `render` const pointing to the `jsdoc2md.render` method does not have its `this` bound to `jsdoc2md`. This works: 

```js
const jsdoc2md = require('jsdoc-to-markdown');

jsdoc2md.render({ source: '/** example doclet */ \n var example = true' }).then(
  console.log
);
```

**Comment by Haroenv** [comment]
Thank you!
