### ISSUE TITLE
Can't install module - 502 Gateway error 

### ISSUE THREAD

**Issue by OEMarshall** [jsdoc2md/jsdoc-to-markdown#193]
![image](https://user-images.githubusercontent.com/11700790/60519332-56becc80-9cb1-11e9-9c55-8f9e8c813d74.png)
This is what I see when I try to visit the NPM page from the Readme and I receive the following when I try to install the package with yarn. 

```
$ yarn add --dev jsdoc-to-markdown
yarn add v1.16.0
[1/4] Resolving packages...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
info There appears to be trouble with the npm registry (returned undefined). Retrying...
⡀ jsdoc-to-markdown/usr/share/yarn/lib/cli.js:66073
            throw new (_errors || _load_errors()).ResponseError(_this3.reporter.lang('requestFailed', description), res.statusCode);
            ^

Error: Request failed "502 Bad Gateway"
    at ResponseError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/share/yarn/lib/cli.js:802:124)
    at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66073:19)
    at Request.self.callback (/usr/share/yarn/lib/cli.js:129590:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/share/yarn/lib/cli.js:130562:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:130484:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
```

**Comment by OEMarshall** [comment]
Realized that this is problem with cloudflare and not the maker's of the package.
