### ISSUE TITLE
Parsing @private - Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by guatedude2** [jsdoc2md/jsdoc-to-markdown#28]
The error I got when running `jsdoc2md({ src: source }).pipe(fs.createWriteStream(output));`

	WARNING: JSDoc does not currently handle ExportDefaultDeclaration nodes. Source file: /Users/Alex/Projects/pixi-cli-server/plugins/class/0.0.1.js, line 102
	events.js:85
		  throw er; // Unhandled 'error' event
				^
	TypeError: Cannot read property 'match' of undefined
		at Object.parseType (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/helpers/helpers.js:260:25)
		at Object.eval (eval at <anonymous> (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:8:108)
		at prog (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:15)
		at execIteration (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:133:19)
		at Object.<anonymous> (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:142:11)
		at Object.eval (eval at <anonymous> (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:34)
		at Object.prog [as fn] (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:15)
		at Object.<anonymous> (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:181:22)
		at Object.eval (eval at <anonymous> (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:35)
		at ret (/Users/Alex/Projects/pixi-cli-server/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)

This happens when there's a jdoc property `@priate` instead of `@private`

**Comment by 75lb** [comment]
fixed in https://github.com/jsdoc2md/dmd/commit/0f134973266e7781c4dfae070db2a67c2aaa1f2c, released in `dmd@1.0.3`.. thanks for the report :+1: .. reinstall your jsdoc2md tool/plugin to pick up the fix.
