### ISSUE TITLE
can't parse typescript file content with Node.js api getTemplateData

### ISSUE THREAD

**Issue by hansonfang** [jsdoc2md/jsdoc-to-markdown#289]
here is the script: 
```js
const rawJsdoc = await jsdoc2md.getTemplateData({
    files: path.join(__dirname, '../src/validator/*.ts'),
    "no-cache": true,
    // source: validatorsSourceCode,
    configure: path.join(__dirname, './jsdoc2md.json')
  });
```
jsdoc2md.json :

```json
{
	"source": {
		"includePattern": ".+\\.ts(doc|x)?$",
		"excludePattern": ".+\\.(test|spec).ts"
	},
	"plugins": [
		"plugins/markdown",
		"node_modules/jsdoc-babel"
	],
	"babel": {
		"extensions": [
			"ts",
			"tsx"
		],
		"ignore": [
			"**/*.(test|spec).ts"
		],
		"babelrc": true
	}
}

```

it all works fine when I run with cli like this:

`jsdoc2md --files ./src/validator/*.ts --configure ./script/jsdoc2md.json > ./script/validator.md`

but it would throw the following error while I run with the above node script:

```sh
node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:72
}, descriptor)), Object.assign(new constructor(), properties));
                               ^

SyntaxError: Unexpected token, expected "," (25:31)
    at instantiate (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:3335:19)
    at Parser.unexpected (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:3373:16)
    at Parser.expect (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:4002:28)
    at Parser.parseBindingList (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:11851:14)
    at Parser.parseFunctionParams (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:15346:24)
    at Parser.parseFunction (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:15324:10)
    at Parser.parseFunctionStatement (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:14925:17)
    at Parser.parseStatementContent (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:14577:21)
    at Parser.parseStatement (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:14533:17)
    at Parser.parseExportDeclaration (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:15913:17)
    at Parser.maybeParseExportDeclaration (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:15859:31)
    at Parser.parseExport (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:15786:29)
    at Parser.parseStatementContent (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:14649:27)
    at Parser.parseStatement (/Users/hanson/iqiyi/common/cobra/node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/lib/index.js:14533:17) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 25, column: 31, index: 483 },
  pos: [Getter/Setter]
}
```

**Comment by hansonfang** [comment]
sorry it turns out the babel's error
