### ISSUE TITLE
object spread operator not supported

### ISSUE THREAD

**Issue by vvo** [jsdoc2md/jsdoc-to-markdown#61]
Modifying any class from https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/src to add:

```js
this.fakeKey = {...this.fakeKey}
```

And running render.js from https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/scripting/output-file-per-class will not output anything.

Indeed the parsing is failing. It seems that the object spread operator is not supported while it should (there's somewhere a "experimentalObjectRestSpread" flag).

It seems to be a pretty tough issue for someone not understanding the full stack, I thought you might have a clue more easily?

**Comment by 75lb** [comment]
hi! did you mean this? 

```js
this.fakeKey =  [ ...this.fakeKey ]
```

**Comment by vvo** [comment]
Hi, no really on an object, this is stage 2 proposal https://github.com/sebmarkbage/ecmascript-rest-spread which means "maybe" but is used everywhere in React examples for instance.

It seems that it should be supported: https://github.com/jsdoc3/jsdoc/search?utf8=%E2%9C%93&q=experimentalObjectRestSpread.

This is the error I get:

```
{ [JSDOC_ERROR: /localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/astnode.js:226
                var key = prop.key.name;
                                  ^

TypeError: Cannot read property 'name' of undefined
    at /localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/astnode.js:226:35
    at Array.forEach (native)
    at exports.nodeToValue (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/astnode.js:225:29)
    at Object.exports.getInfo (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/astnode.js:327:26)
    at Visitor.makeSymbolFoundEvent (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/visitor.js:509:33)
    at Visitor.visitNode (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/visitor.js:453:18)
    at Visitor.visit (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/visitor.js:375:27)
    at Walker.recurse (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/walker.js:596:44)
    at Parser._walkAst (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/parser.js:266:18)
    at Parser._parseSourceCode (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/parser.js:257:18)
    at Parser.parse (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/lib/jsdoc/src/parser.js:178:18)
    at Object.module.exports.cli.parseFiles (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/cli.js:362:42)
    at module.exports.cli.main (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/cli.js:226:14)
    at Object.module.exports.cli.runCommand (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/cli.js:180:5)
    at /localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/jsdoc.js:103:9
    at Object.<anonymous> (/localdir/jsdoc-to-markdown/node_modules/jsdoc-parse/node_modules/jsdoc-api/node_modules/jsdoc-75lb/jsdoc.js:104:3)] name: 'JSDOC_ERROR' }
```

**Comment by vvo** [comment]
This syntax is used to do things like: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20obj%20%3D%20%7Bone%3A%201%7D%3B%0Avar%20obj2%20%3D%20%7B...obj%2C%20two%3A%202%7D%0Aconsole.log(obj2)

**Comment by 75lb** [comment]
hmm, i've never seen jsdoc fail inside `jsdoc/src/astnode.js` before.. if you think jsdoc3 *should* support this feature but is failing then we may have found a bug.. i will have a play with it this evening and make a suggestion to jsdoc3 if necessary.

**Comment by vvo** [comment]
OK to test it I only modified one of the example to add this

```
this.fakeKey = {...this.fakeKey}
```

in a constructor, then render.js fails

**Comment by vvo** [comment]
Hope you can help us!

**Comment by 75lb** [comment]
this syntax `this.fakeKey = {...this.fakeKey}` does not parse with jsdoc.. i tried using jsdoc directly on the code and it fails.. i'm afraid you need to raise an issue with jsdoc3, it is outside my control.. link back to this thread so i can monitor the issue, please.

**Comment by vvo** [comment]
Ok thanks, I will try to do a reduced test case on the jsdoc module and open an issue

**Comment by 75lb** [comment]
simple reproduction case.. 

input: 
```js
const array = [ 1, 2, 3 ]
const object = { ...array }
```

output: 
```
$ jsdoc -X spread-issue.js
/Users/lloyd/Documents/75lb/jsdoc/lib/jsdoc/src/astnode.js:226
                var key = prop.key.name;
                                  ^

TypeError: Cannot read property 'name' of undefined
    at /Users/lloyd/Documents/75lb/jsdoc/lib/jsdoc/src/astnode.js:226:35
```

**Comment by vvo** [comment]
should not work with an array but just an object:

```
const obj1 = {one: 1}
const obj2 = { ...obj1, two: 2 } // {one: 1, two: 2}
```

**Comment by 75lb** [comment]
ah, ok - thanks..

**Comment by vvo** [comment]
Ok done here: https://github.com/jsdoc3/jsdoc/pull/1141

**Comment by vvo** [comment]
Can you maybe backport this commit in your jsdoc fork so we can move on... :)

**Comment by 75lb** [comment]
Yep :-) will look at that tonight.

**Comment by 75lb** [comment]
patch [landed in the jsdoc2md fork](https://github.com/jsdoc2md/jsdoc/commit/92e865f7095f714f6754f39ff2984112eac02d55), released in v3.5.2.. thanks again! please `npm update`

**Comment by vvo** [comment]
weeeeeeeeee!!!

**Comment by 75lb** [comment]
hehe :)

**Comment by vvo** [comment]
quick update, it was merged in main jsdoc project
