### ISSUE TITLE
Doesn't read documentation from files with underscores

### ISSUE THREAD

**Issue by zakkudo** [jsdoc2md/jsdoc-to-markdown#80]
For some reason jsdoc2md won't read files that have underscores.

```
jsdoc2md --verbose __module__.js
JSDOC_ERROR: Jsdoc failed.
    at Explain.verifyOutput (/usr/local/lib/node_modules/jsdoc-to-markdown/node_modules/jsdoc-api/lib/jsdoc.js:110:19)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/jsdoc-to-markdown/node_modules/jsdoc-api/lib/jsdoc.js:149:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

But when I rename `__module__.js` to `module.js`:

```
jsdoc2md --verbose module.js
<a name="app"></a>
## app : <code>object</code>
The application

**Kind**: global namespace
```

**Comment by 75lb** [comment]
confirmed, thanks for letting me know!

**Comment by 75lb** [comment]
sorry for the slow reply.. for some reason, jsdoc ignores files starting with `_` by default.. from their docs:

> Any file starting with an underscore or in a directory starting with an underscore will be ignored (source.excludePattern);

sorry, but you will need to supply your own [jsdoc conf file](http://usejsdoc.org/about-configuring-jsdoc.html) to jsdoc2md, via the `--conf` property.. please read [this issue](https://github.com/jsdoc3/jsdoc/issues/308) for tips.. let me know how you get on.

**Comment by zakkudo** [comment]
Thanks!  Sorry for making you read the documentation for me.

**Comment by 75lb** [comment]
it's ok, i thought it was a bug at first..
